- name: configure frint end server
  hosts: frontend
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: enable and start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
    - name: delete html directory
      ansible.builtin.file:
        state: absent
        path: /usr/share/nginx/html

    - name: create html directory
      ansible.builtin.file:
        state: directory
        path: /usr/share/nginx/html

    - name: download frontend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip

    - name: unzip the zip file
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: copying expense conf file
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: enable and start nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
